---
- hosts: all
  tasks:
    - name: change permissions
      file:
        path: /var/lib/tomcat9
        mode: 0777
        recurse: yes
        state: directory
    - name: deploy code
      copy:
        src: java-example.war
        dest: /var/lib/tomcat9/webapps/java-example.war
    - name: restart tomcat service
      service:
        name: tomcat9
        state: restarted 